FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Copies the contents of the directory the Dockerfile is in into the image.
COPY ./Application /Applicaiton

# Set working directory for the ENTRYPOINT
#WORKDIR Application

# Run the application
ENTRYPOINT ["dir"]
#ENTRYPOINT ["dotnet", "TixFactory.Logging.Service.dll"]
