FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Copies the contents of the directory the Dockerfile is in into the image.
COPY . /Applicaiton

#WORKDIR Application
ENTRYPOINT ["dir"]
#ENTRYPOINT ["dotnet", "TixFactory.Logging.Service.dll", "--urls=http://localhost:5000"]
