version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      discovery.seed_hosts: 127.0.0.1
      discovery.type: single-node
      bootstrap.memory_lock: true
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      tix-factory:
        aliases:
          - elasticsearch
          - es.tixfactory.systems
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - durable-storage:/usr/share/elasticsearch/data
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    networks:
      tix-factory:
        aliases:
          - kibana
          - logging.tixfactory.systems
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
  logging-service:
    image: tixfactory/logging-service:latest
    container_name: logging-service
    environment:
      LoggingServiceAllowedIpAddressesCsv: 127.0.0.1 # ME: Replace this IP address with public facing IP address!
      ElasticSearchEndpoint: http://es.tixfactory.systems:9200/tix-factory/logs
    networks:
      tix-factory:
        aliases:
          - logging-service
          - monitoring.tixfactory.systems
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
    restart: always

networks:
  tix-factory:
    name: tix-factory

volumes:
  durable-storage:
    driver: local