version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      discovery.seed_hosts: 127.0.0.1
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      tix-factory:
        aliases:
          - elasticsearch
          - tix-factory-monitoring
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    networks:
      tix-factory:
        aliases:
          - kibana
    ports:
      - "5601:5601"
    restart: always
  logging-service:
    image: tixfactory/monitoring:latest
    container_name: logging-service
    networks:
      tix-factory:
        aliases:
          - logging-service
    ports:
      - "80:80"
    restart: always
networks:
  tix-factory:
    name: tix-factory