name: TixFactory.Logging.Service

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Create Build Directories
      run: |
        mkdir -p ./Build/NuGet/Cache
        mkdir -p ./Build/Publish/Application
        cp ./Services/Logging/TixFactory.Logging.Service/Dockerfile ./Build/Publish/Dockerfile
    - name: Restore
      run: dotnet restore ./Services/Logging/TixFactory.Logging.Service.sln
    - name: Build + Publish
      run: dotnet publish ./Services/Logging/TixFactory.Logging.Service/TixFactory.Logging.Service.csproj --output ./Build/Publish/Application --configuration Release --runtime linux-x64 --self-contained true
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./Build/Publish
    - name: Create Docker Image
      run: docker build --tag tix-factory/monitoring:latest .
    - name: Login to DockerHub
      # if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    - name: Push Docker Image
      # if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push tixfactory/monitoring:latest
