name: TixFactory.Logging.Service

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Create Build Directories
      run: |
        mkdir -p ./Build/NuGet/Cache
        mkdir -p ./Build/Publish
    - name: Restore
      run: dotnet restore ./Services/Logging/TixFactory.Logging.Service.sln
    - name: Build
      run: dotnet build ./Services/Logging/TixFactory.Logging.Service.sln --configuration Release --runtime linux-x64
    - name: Publish
      run: dotnet publish ./Services/Logging/TixFactory.Logging.Service/TixFactory.Logging.Service.csproj --output ./Build/Publish --self-contained true --no-build
    outputs:
      publish: ./Build/Publish
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'main' }}
    steps:
    - name: Upload Docker Image
      run: dir ./Build/Publish
