name: TixFactory.Logging.Service

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Create Build Directories
      run: |
        mkdir -p ./Build/NuGet/Cache
        mkdir -p ./Build/Publish
    - name: Restore
      run: dotnet restore ./Services/Logging/TixFactory.Logging.Service.sln
    - name: Build + Publish
      run: dotnet publish ./Services/Logging/TixFactory.Logging.Service/TixFactory.Logging.Service.csproj --output ./Build/Publish --configuration Release --runtime linux-x64 --self-contained true
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./Build/Publish
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download Publish Artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: ./Build/Publish 
    - name: Log Artifact Contents
      run: dir ./Build/Publish
